import Groq from 'groq-sdk';

// Constants
const AI_MODEL = process.env.GROQ_AI_MODEL || 'llama-3.3-70b-versatile';

// ✅ Singleton Groq client
let groq = null;
let isGroqInitialized = false;

try {
  if (!process.env.GROQ_API_KEY) {
    console.warn('⚠️ GROQ_API_KEY is not set');
  } else {
    if (!process.env.GROQ_API_KEY.startsWith('gsk_')) {
      console.warn('⚠️ GROQ_API_KEY format is invalid. Should start with "gsk_"');
    }
    groq = new Groq({
      apiKey: process.env.GROQ_API_KEY,
    });
    isGroqInitialized = true;
    console.log('✅ Groq AI service initialized');
  }
} catch (error) {
  console.error('❌ Failed to initialize Groq:', error.message);
  groq = null;
  isGroqInitialized = false;
}

export const isGroqAvailable = () => isGroqInitialized && !!groq;

// ✅ SYSTEM_PROMPT - AI extracts metadata, title generated by backend
const SYSTEM_PROMPT = `You are an intent classifier for a voice note app. Extract information from the user's transcript.

CRITICAL: You MUST extract the date and time if mentioned. Pay special attention to phrases like "at 7 pm", "tomorrow at 2 PM", "July 20 at 7pm".

DO NOT generate a title. The title will be created by the system.

Extract these fields:
- type: one of "Note", "Task", "Reminder", "Event"
- date: the date mentioned (e.g., "today", "tomorrow", "July 20", "20 July 2026", "next Friday")
- time: the time mentioned (e.g., "7 PM", "7pm", "2:30 PM", "14:00")
- endTime: end time if mentioned (e.g., "5 PM")
- duration: duration if mentioned (e.g., "1 hour", "30 minutes")
- person: name of a person if mentioned
- repeat: if mentioned (e.g., "daily", "weekly")
- location: if mentioned (e.g., "Zoom", "Office")
- items: array of items (for shopping/task lists)
- subtasks: array of subtasks (for task lists)

Classification rules:
- "Event": meetings, appointments, calls with a specific time and another person
- "Reminder": something to be reminded of at a specific time, often personal
- "Task": something to get done, may or may not have a deadline
- "Note": general thoughts, ideas, or information with no action/time

Date/time rules:
- "at 7 pm" → time: "7 PM"
- "tomorrow at 7 pm" → date: "tomorrow", time: "7 PM"
- "July 20 at 7pm" → date: "July 20", time: "7 PM"
- "Call mom at 9 PM" → time: "9 PM", person: "mom"
- "Buy milk and eggs" → items: ["milk", "eggs"]

Return ONLY valid JSON. No explanations, no markdown.

Examples:
{"type":"Event","person":"James","date":"tomorrow","time":"7 PM"}
{"type":"Event","person":"James","date":"20 July 2026","time":"7 PM","location":"Zoom"}
{"type":"Reminder","person":"John","date":"today","time":"2 PM"}
{"type":"Reminder","person":"mom","time":"9 PM"}
{"type":"Task","items":["milk","eggs","bread"]}
{"type":"Task","subtasks":["research","write","submit"]}
{"type":"Note"}`;

function extractJSON(content) {
  const markdownMatch = content.match(/```json\s*([\s\S]*?)\s*```/);
  if (markdownMatch) {
    return markdownMatch[1];
  }

  const start = content.indexOf('{');
  const end = content.lastIndexOf('}');
  if (start !== -1 && end !== -1 && start < end) {
    return content.substring(start, end + 1);
  }

  return null;
}

/**
 * ✅ Generate descriptive title from parsed data - PRESERVES ALL DETAILS
 */
function generateTitle(parsed, transcript) {
  const { type, person, items, subtasks, date, location, time } = parsed;
  
  // Clean transcript for fallback
  const cleanTranscript = transcript.trim();
  
  let title = '';
  
  switch (type) {
    case 'Event':
      // ✅ Preserve person, location, and date
      if (person && location) {
        title = `Meeting with ${person} at ${location}`;
      } else if (person) {
        title = `Meeting with ${person}`;
      } else if (location) {
        title = `Event at ${location}`;
      } else {
        // Use first few words from transcript
        const words = cleanTranscript.split(' ').slice(0, 6);
        title = words.join(' ');
        title = title.charAt(0).toUpperCase() + title.slice(1);
      }
      break;

    case 'Reminder':
      // ✅ Preserve person and action
      if (person) {
        title = `Call ${person}`;
      } else if (location) {
        title = `Reminder at ${location}`;
      } else {
        // Use first few words from transcript
        const words = cleanTranscript.split(' ').slice(0, 5);
        title = words.join(' ');
        title = title.charAt(0).toUpperCase() + title.slice(1);
      }
      break;

    case 'Task':
      // ✅ Preserve items and subtasks
      if (items && items.length > 0) {
        const itemList = items.join(', ');
        title = `Buy ${itemList}`;
      } else if (subtasks && subtasks.length > 0) {
        const taskList = subtasks.join(', ');
        title = `Complete ${taskList}`;
      } else {
        // Use first few words from transcript
        const words = cleanTranscript.split(' ').slice(0, 5);
        title = words.join(' ');
        title = title.charAt(0).toUpperCase() + title.slice(1);
      }
      break;

    case 'Note':
    default: {
      // ✅ Use first 5-6 words from transcript for Notes
      const words = cleanTranscript.split(' ').slice(0, 6);
      title = words.join(' ');
      title = title.charAt(0).toUpperCase() + title.slice(1);
      if (words.length === 6) {
        title += '...';
      }
      return title || 'Note';
    }
  }
  
  // ✅ Add date if present (with year) and not already in title
  if (date) {
    const hasYear = /\b(19|20)\d{2}\b/.test(date);
    if (hasYear) {
      const cleanDate = date.replace(/(\d+)(st|nd|rd|th)/, '$1');
      // Only add if not already in title
      if (!title.includes(cleanDate)) {
        title += ` (${cleanDate})`;
      }
    }
  }
  
  // ✅ Add time if present and not already in title
  if (time && !title.includes(time)) {
    // Only add if title is short enough
    if (title.length < 30) {
      title += ` at ${time}`;
    }
  }
  
  return title;
}

export const aiParsingService = async (transcript) => {
  const trimmedTranscript = transcript.trim();
  
  // ✅ Fallback - use transcript for title
  const fallback = {
    type: 'Note',
    title: trimmedTranscript.slice(0, 60) + (trimmedTranscript.length > 60 ? '...' : ''),
    date: null,
    time: null,
    endTime: null,
    duration: null,
    repeat: null,
    location: null,
    person: null,
    items: [],
    subtasks: [],
  };

  if (!isGroqAvailable()) {
    console.warn('⚠️ Groq AI not initialized. Falling back to Note.');
    return fallback;
  }

  console.log('🤖 Extracting metadata from:', trimmedTranscript);

  try {
    const response = await groq.chat.completions.create({
      model: AI_MODEL,
      messages: [
        { role: 'system', content: SYSTEM_PROMPT },
        { role: 'user', content: `Transcript: "${trimmedTranscript}"` },
      ],
      temperature: 0,
      top_p: 1,
      max_tokens: 250,
      response_format: { type: 'json_object' },
    });

    const content = response.choices[0]?.message?.content || '';
    console.log('🤖 AI raw response:', content);

    const jsonString = extractJSON(content);
    if (!jsonString) {
      console.warn('⚠️ No JSON found in AI response');
      return fallback;
    }

    const parsed = JSON.parse(jsonString);
    console.log('✅ Parsed AI result:', JSON.stringify(parsed, null, 2));

    // ✅ Generate descriptive title from parsed data
    const title = generateTitle(parsed, trimmedTranscript);
    console.log('📝 Generated title:', title);

    return {
      type: parsed.type || 'Note',
      title: title,
      date: parsed.date || null,
      time: parsed.time || null,
      endTime: parsed.endTime || null,
      duration: parsed.duration || null,
      repeat: parsed.repeat || null,
      location: parsed.location || null,
      person: parsed.person || null,
      items: Array.isArray(parsed.items) ? parsed.items : [],
      subtasks: Array.isArray(parsed.subtasks) ? parsed.subtasks : [],
    };
  } catch (error) {
    console.error('❌ AI parsing error:', error.message);
    return fallback;
  }
};

export const generateBriefingTextService = async (items) => {
  try {
    if (!items || items.length === 0) {
      return "Good morning! You have no tasks or events scheduled for today. Enjoy your day! 😊";
    }

    const limitedItems = items.slice(0, 10);

    if (isGroqAvailable()) {
      try {
        const itemsText = limitedItems.map((item, index) => {
          const time = item.startTime
            ? new Date(item.startTime).toLocaleTimeString('en-US', {
                hour: '2-digit',
                minute: '2-digit'
              })
            : 'No time set';
          return `${index + 1}. ${item.title} (${item.type})${item.startTime ? ` at ${time}` : ''}`;
        }).join('\n');

        const prompt = `You are a friendly personal assistant. Create a brief, warm morning briefing based on today's schedule.

Today's items:
${itemsText}

Provide a concise summary (2-3 sentences) that:
1. Greets the user warmly
2. Mentions the total number of items
3. Highlights the most important or time-sensitive items
4. Has a positive, encouraging tone

Keep it natural and conversational.`;

        const chatCompletion = await groq.chat.completions.create({
          messages: [
            { role: "system", content: "You are a friendly personal assistant providing a brief morning briefing." },
            { role: "user", content: prompt },
          ],
          model: AI_MODEL,
          temperature: 0.7,
          max_tokens: 150,
        });

        const aiSummary = chatCompletion.choices[0]?.message?.content;
        if (aiSummary) return aiSummary;
      } catch (aiError) {
        console.error('❌ AI briefing generation failed:', aiError.message);
      }
    }

    // Fallback
    const events = items.filter(i => i.type === 'Event' && i.status === 'active');
    const tasks = items.filter(i => i.type === 'Task' && i.status === 'active');
    const reminders = items.filter(i => i.type === 'Reminder' && i.status === 'active');
    const notes = items.filter(i => i.type === 'Note' && i.status === 'active');

    let briefing = "🌅 Good morning! Here's your day: ";
    if (events.length > 0) {
      briefing += `You have ${events.length} event${events.length > 1 ? 's' : ''}: `;
      briefing += events.map(e => e.title).join(', ');
      briefing += '. ';
    }
    if (tasks.length > 0) {
      briefing += `You have ${tasks.length} task${tasks.length > 1 ? 's' : ''} to complete. `;
    }
    if (reminders.length > 0) {
      briefing += `Don't forget your ${reminders.length} reminder${reminders.length > 1 ? 's' : ''}. `;
    }
    if (notes.length > 0) {
      briefing += `You have ${notes.length} note${notes.length > 1 ? 's' : ''} saved. `;
    }
    briefing += `Have a productive day! 🚀`;
    return briefing;
  } catch (error) {
    console.error('❌ Briefing generation error:', error);
    return `Good morning! You have ${items.length} items scheduled for today. Have a great day! 🌟`;
  }
};

export default {
  aiParsingService,
  generateBriefingTextService,
  isGroqAvailable,
};